name = "TinyBenchmarks"
uuid = "3cd17ee1-07c7-427c-802e-f442bea97d9d"
authors = ["Ludovic Raess <ludovic.rass@gmail.com> and Ivan Utkin <iutkin@ethz.ch>"]
version = "0.2.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
TinyKernels = "f7cbc414-f748-44bf-86e6-e44e9a55e39d"
